version: '3.8'

services:
  web:
    build: .
    ports:
      - "5121:5121"
    environment:
      - FLASK_ENV=development
      - DB_URI=sqlite:///flask-api-db.db
      - FLASK_KEY=your-secret-key-here
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=5121

  # If you want to use PostgreSQL instead of SQLite:
  # db:
  #   image: postgres
  #   environment:
  #     POSTGRES_USER: youruser
  #     POSTGRES_PASSWORD: yourpassword
  #     POSTGRES_DB: yourdb
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/

# volumes:
#   postgres_data: